{{- range $name, $service := .Values.service -}}
  {{- if $service.enabled -}}
---  
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storj-storagenode.fullname" . }}-{{ $name }}
  labels:
    {{- include "storj-storagenode.labels" . | nindent 4 }}
  annotations:
    {{- with $service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  {{- with $service }}
  type: {{ .type }}
  {{ if .loadBalancerIP }}loadBalancerIP: {{ .loadBalancerIP }}{{ end }}
  ports:
    - port: {{ .port }}
      targetPort: storagenode
      {{- if $port.protocol }}
      {{- if or ( eq $port.protocol "HTTP" ) ( eq $port.protocol "HTTPS" ) ( eq $port.protocol "TCP" ) }}
      protocol: TCP
      {{- else }}
      protocol: {{ $port.protocol }}
      {{- end }}
      {{- else }}
      protocol: TCP
      {{- end }}
      name: storagenode
      {{ if .nodePort }}nodePort: {{ .nodePort }}{{ end }}
  {{- end }}
  selector:
    {{- include "storj-storagenode.selectorLabels" . | nindent 4 }}
{{- end }}
